import { chromium } from 'playwright';
const url=process.argv[2]||'https://indiauncharted.com/yoga-holiday-in-goa/';
const width=+(process.argv[3]||1440);
const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const b=await chromium.launch();const ctx=await b.newContext({viewport:{width,height:900},deviceScaleFactor:1,userAgent:UA});
const p=await ctx.newPage();await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForTimeout(2500);
await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=800){scrollTo(0,y);await new Promise(r=>setTimeout(r,40));}scrollTo(0,0);});
const g=(sel,props)=>{return {sel,...Object.fromEntries((()=>{const el=document.querySelector(sel);if(!el)return[['MISSING',true]];const cs=getComputedStyle(el);const r=el.getBoundingClientRect();const o=[['x',Math.round(r.x)],['y',Math.round(r.y+scrollY)],['w',Math.round(r.width)],['h',Math.round(r.height)]];for(const pr of props)o.push([pr,cs[pr]]);return o;})())};};
const res=await p.evaluate(({})=>{
  const out={};
  const grab=(name,sel,props)=>{const el=document.querySelector(sel);if(!el){out[name]={MISSING:sel};return;}const cs=getComputedStyle(el);const r=el.getBoundingClientRect();const o={x:Math.round(r.x),y:Math.round(r.y+scrollY),w:Math.round(r.width),h:Math.round(r.height)};for(const pr of props)o[pr]=cs[pr];out[name]=o;};
  const T=['fontSize','lineHeight','fontFamily','fontWeight','color','marginTop','marginBottom','textAlign','paddingTop','paddingBottom','paddingLeft','paddingRight','maxWidth','backgroundColor'];
  grab('subheader','#Subheader',['paddingTop','paddingBottom','minHeight','backgroundColor','backgroundImage','textAlign']);
  grab('subheaderTitle','#Subheader h1.title',T);
  grab('content','#Content',['maxWidth','paddingLeft','paddingRight','backgroundColor']);
  grab('contentWrapper','#Content .content_wrapper',['maxWidth','width','paddingLeft','paddingRight']);
  grab('sectionsGroup','#Content .sections_group',['maxWidth','width']);
  grab('post','#post-778',['maxWidth','width','marginLeft','marginRight','paddingLeft','paddingRight']);
  grab('sectionPostHeader','.section-post-header .section_wrapper',['maxWidth','width','paddingLeft','paddingRight']);
  grab('featImgFrame','.single-photo-wrapper.image .image_frame',['maxWidth','width','marginLeft','marginRight','textAlign']);
  grab('featImg','.wp-post-image',['width','height','maxWidth']);
  grab('theContent','.the_content_wrapper',['maxWidth','width','paddingLeft','paddingRight']);
  grab('p1','.the_content_wrapper p',T);
  grab('h2','.the_content_wrapper h2',T);
  grab('ul','.the_content_wrapper ul',['marginTop','marginBottom','paddingLeft']);
  grab('li','.the_content_wrapper li',T.concat(['listStyleType']));
  grab('authorBox','.section-post-about .section_wrapper',['maxWidth','width','paddingLeft','paddingRight']);
  grab('authorWrap','.author-box-wrapper',['backgroundColor','padding','border','borderRadius','display','alignItems']);
  grab('authorH5','.desc-wrapper h5',T);
  grab('relatedWrap','.section-post-related .section_wrapper',['maxWidth','width','paddingLeft','paddingRight']);
  grab('relatedH4','.section-related-adjustment > h4',T);
  grab('relatedUl','.section-related-ul',['display','gap']);
  grab('relatedCol','.section-related-ul .column',['width','marginLeft','marginRight']);
  grab('relatedDescH4','.post-related .desc h4',T);
  grab('relatedDescH4a','.post-related .desc h4 a',['color','fontSize']);
  grab('readmore','.post-related .button','fontSize,color,backgroundColor,padding,borderRadius'.split(','));
  grab('caption','.wp-caption-text',T);
  grab('dateLabel','.date_label',T);
  grab('commentsWrap','.section-post-comments .section_wrapper',['maxWidth','width','paddingLeft','paddingRight']);
  grab('replyTitle','#reply-title',T);
  grab('commentNotes','.comment-notes',T);
  grab('label','.comment-form-comment label',T);
  grab('textarea','#comment',['width','height','border','padding','backgroundColor']);
  grab('inputAuthor','#author',['width','height','border','padding']);
  grab('submit','#submit',['fontSize','color','backgroundColor','padding','borderRadius','border']);
  // section vertical paddings
  grab('secPostHeaderOuter','.section-post-header',['paddingTop','paddingBottom']);
  grab('secContentOuter','.section.the_content',['paddingTop','paddingBottom','marginTop','marginBottom']);
  grab('secRelatedOuter','.section-post-related',['paddingTop','paddingBottom','backgroundColor']);
  grab('secCommentsOuter','.section-post-comments',['paddingTop','paddingBottom']);
  grab('secAboutOuter','.section-post-about',['paddingTop','paddingBottom']);
  return out;
},{});
console.log(JSON.stringify(res,null,1));
await b.close();
