import { chromium } from 'playwright';
const url=process.argv[2];const UA='Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1';
const b=await chromium.launch();const p=await(await b.newContext({viewport:{width:360,height:800},deviceScaleFactor:1,userAgent:UA,isMobile:true})).newPage();
await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForTimeout(2500);
await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=600){scrollTo(0,y);await new Promise(r=>setTimeout(r,30));}scrollTo(0,0);});
const isLive=url.includes('indiauncharted');
const res=await p.evaluate((isLive)=>{const out={};const grab=(n,sel,props)=>{const el=document.querySelector(sel);if(!el){out[n]={M:sel};return;}const cs=getComputedStyle(el);const r=el.getBoundingClientRect();const o={x:Math.round(r.x),w:Math.round(r.width)};for(const pr of props)o[pr]=cs[pr];out[n]=o;};
 const bodySel=isLive?'.the_content_wrapper':'.art-body';
 const pSel=isLive?'.the_content_wrapper p':'.art-body p';
 const h2Sel=isLive?'.the_content_wrapper h2':'.art-body h2';
 const featSel=isLive?'.wp-post-image':'.art-featured img';
 const relSel=isLive?'.post-related':'.art-related__card';
 const relImgSel=isLive?'.post-related img.wp-post-image':'.art-related__thumb img';
 grab('body',bodySel,['fontSize','lineHeight','paddingLeft','paddingRight']);
 grab('p',pSel,['fontSize','lineHeight','marginBottom']);
 grab('h2',h2Sel,['fontSize','lineHeight']);
 grab('feat',featSel,['width','height']);
 grab('relCard',relSel,['width']);
 grab('relImg',relImgSel,['width','height']);
 out.docH=document.documentElement.scrollHeight;return out;},isLive);
console.log(url.includes('indiauncharted')?'LIVE':'PROTO',JSON.stringify(res,null,1));await b.close();
