import { chromium } from 'playwright';
const url=process.argv[2], out=process.argv[3];
const b=await chromium.launch(); const p=await (await b.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1})).newPage();
await p.goto(url,{waitUntil:'networkidle',timeout:30000}).catch(()=>{});
await p.waitForTimeout(2500);
await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=800){scrollTo(0,y);await new Promise(r=>setTimeout(r,80));}scrollTo(0,0);});
await p.waitForTimeout(500);
await p.screenshot({path:out,fullPage:true});
console.log('shot',out);
await b.close();
